# Generated by Django 6.0.5 on 2026-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('muallif', models.CharField(max_length=100)),
                ('matn', models.TextField()),
                ('korishlar', models.PositiveIntegerField(default=0)),
                ('chop_etilgan', models.BooleanField(default=False)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
